language: python

python:
  - 2.7

env:
  - DJANGO_VERSION=1.4.8
  - DJANGO_VERSION=1.5.1

install:
  - make setup
  - pip install django==$DJANGO_VERSION

script: make test

after_success:
  - coveralls
